name: SSMPublish Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  tests:
    name: Tests and Coverage
    strategy:
      matrix:
        version: [14.19.3, 16, 18, 20, 22]
    runs-on: ubuntu-latest

    steps:
      - name: Acquire Github Commit Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: mysense-ai
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          registry-url: 'https://npm.pkg.github.com'
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Tests
        run: |
          yarn lint
          yarn test
          
      - name: Build and publish to NPM
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Building..."
          yarn build:ci

          echo "Deploying..."
          yarn semantic-release
